### ISSUE TITLE
Issue Feed

### ISSUE THREAD

**Issue by jmbarne3** [UCF/Pegasus-Theme#3]
We need to make sure issues that haven't been "published" yet don't show up in the issue list.

**Comment by cjg89** [comment]
We filter results in the issue list to only include those that are published: https://github.com/UCF/Pegasus-Theme/blob/master/functions.php#L1480

I'm also not able to make a draft issue appear in this list when testing locally.

Going to close this issue, but please re-open if we see unpublished issues showing up in this feed in the future.
