### ISSUE TITLE
Utilize our Social plugin instead of the current built in social share buttons

### ISSUE THREAD

**Issue by cadie** [UCF/Pegasus-Theme#86]
The current social share buttons are outdated style-wise and content-wise. 

Replace the social buttons on the sub-footer, header, and story template. Also, ensure that older version's social functions do not conflict with the UCF-Social-Plugin's functions.

Changes were previously made to the v6 footer file but reverted since it was out of scope of that PR: See https://github.com/UCF/Pegasus-Theme/commit/132c2a8c978b6df2023455da578bd4ab41b1c5e3. Those should be good to cherry pick for these updates.

**Comment by cjg89** [comment]
Adding a note for whoever picks this up: `socialButtonTracking()` in v6/static/js/script.js will need to be updated to accommodate buttons generated by our social plugin.
